SET NAMES UTF8;
DROP DATABASE IF EXISTS	rw;
CREATE DATABASE rw CHARSET=UTF8;
USE rw;
CREATE TABLE rw_user(
	uid INT PRIMARY KEY AUTO_INCREMENT,
	uname VARCHAR(32),
	upwd VARCHAR(32),
	email VARCHAR(64),
	phone VARCHAR(16),
	gender INT
);